### ISSUE TITLE
组件里使用 ref 和使用一个局部变量来存储 graph 实例的区别?

### ISSUE THREAD

**Issue by hacker0limbo** [baizn/g6-in-react#14]
在[官网](https://g6.antv.vision/zh/docs/manual/advanced/g6InReact)包括这个仓库里面, 我发现似乎都是通过使用 `let graph = null` 来生成一个图实例, 然后在 `useEffect()` 里面做图的数据插入和渲染. 我个人疑惑在于如果我将图实例绑定在一个 `ref` 上有什么区别? 具体代码可能如下:

```javascript
export default function () {
  const ref = React.useRef(null);
  // 改成使用 ref 的形式
  const graphRef = React.useRef(null);

  useEffect(() => {
    graphRef.current = new G6.Graph({
      // ...
    })

    graphRef.current.data(data);
    graphRef.current.render();
  }, []);

  return <div ref={ref}></div>;
}
```

个人想知道通过使用 `let graph = null` 这种局部变量的方式和使用 `const graphRef = React.useRef(null)` 这种方式具体有什么区别, 或者说, 使用哪种形式更好, 为什么?

**Comment by tequilaNiu** [comment]
> 在[官网](https://g6.antv.vision/zh/docs/manual/advanced/g6InReact)包括这个仓库里面, 我发现似乎都是通过使用 `let graph = null` 来生成一个图实例, 然后在 `useEffect()` 里面做图的数据插入和渲染. 我个人疑惑在于如果我将图实例绑定在一个 `ref` 上有什么区别? 具体代码可能如下:
> 
> ```js
> export default function () {
>   const ref = React.useRef(null);
>   // 改成使用 ref 的形式
>   const graphRef = React.useRef(null);
> 
>   useEffect(() => {
>     graphRef.current = new G6.Graph({
>       // ...
>     })
> 
>     graphRef.current.data(data);
>     graphRef.current.render();
>   }, []);
> 
>   return <div ref={ref}></div>;
> }
> ```
> 
> 个人想知道通过使用 `let graph = null` 这种局部变量的方式和使用 `const graphRef = React.useRef(null)` 这种方式具体有什么区别, 或者说, 使用哪种形式更好, 为什么?

可以参考下react官网中的这个问题：https://zh-hans.reactjs.org/docs/hooks-faq.html
