### ISSUE TITLE
demo图和运行出来的项目不一样😂

### ISSUE THREAD

**Issue by huanghui1** [baizn/g6-in-react#24]

**Comment by huanghui1** [comment]
把pages/index.js里的App组件替换成`import App from './app.js';`解决了。

**Comment by SeekPoint** [comment]
改了之后出现

ERROR in ./pages/app.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable.js' in 'C:\react-graph\g6-in-react\pages'
 @ ./pages/app.js 1:0-45
 @ ./pages/index.js
 @ multi webpack-dev-server/client?http://localhost:8080 ./pages/index.js
Child HtmlWebpackCompiler:


我升级了版本：
  "dependencies": {
    "@antv/g6": "^4.7.0",
    "antd": "^4.23.0",
    "html-webpack-plugin": "^4.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "webpack": "^4.42.1"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.9.5",
    "@babel/preset-react": "^7.9.4",
    "@babel/core": "^7.9.6",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.5.2",
    "postcss-loader": "^3.0.0",
    "style-loader": "^1.1.4",
    "ts-loader": "^7.0.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
