### ISSUE TITLE
readme中的图片是哪个例子，怎么运行的

### ISSUE THREAD

**Issue by SeekPoint** [baizn/g6-in-react#25]

**Comment by cendolkeropok** [comment]
我跑出来也不一样 不知道readme是哪个例子的

**Comment by hitao123** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/16607714/197665020-f4ee0bab-e6c7-42d4-882b-c270d29a38c7.png">
把这里的换成 app
